repository: sproogen/resume-theme
favicon: images/favicon.ico
version: 2

# Personal info
name: Amir H. Farnaghizad
title: Biotechnology Student



# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: amirfarnzad
email: amirfarnzad@yahoo.com
github_username:  amirfarnzad
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: amirfarnzad
linkedin_username: amirfarnzad
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
# url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  **CV: [PDF](https://amirfarnzad.github.io/CV.pdf)**
  
  As a dedicated <mark>Biotechnology</mark> student with a deep passion for exploring the complexities of science and business,
  I am driven by a strong interest in pursuing a Master's degree in <mark>Business Management</mark>.
  This stems from my recognition of the critical role that effective business strategies play in the successful translation of biotechnological breakthroughs into practical applications that benefit society.
  

content:
 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Islamic Azad University
        caption: 2021 - 2025
        sub_title: Bachelor of Science, Biotechnology
     
      - layout: top-middle
        title: National Organization for Development of Exceptional Talents
        caption: 2015 - 2021
        sub_title: Student, Science
      

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
