repository: moneuron/intCV
favicon: images/favicon.ico

version: 2
darkmode: never

last_update: Jul 31, 2024

name: Amir H. Farnaghizad
title: Biotechnology Student

email: amir@int-n.info
github_username:  amirfarnzad
in_username: amirfarnzad
googlescholar_username: 0A0A0A
orcid_username: 0000-0000-0000-0000

about_profile_image: images/profile.jpg
about_content: |
  **CV: [PDF](https://amirfarnzad.github.io/cv.pdf)**
  
  As a dedicated <mark>Biotechnology</mark> student with a deep passion for exploring the complexities of science and business,  

content:
  - title: Publications
    layout: pub
    content:
      - title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,"
        authors: <b>Farnaghizad, A.</b>, ...,
        journal: eiusmod
        link: 
      

remote_theme: moneuron/intCV

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
