repository: mo-shakiba/intCV
favicon: images/favicon.ico

version: 2
darkmode: never

last_update: Apr 11, 2024

name: Amir H. Farnaghizad
title: Biotechnology Student

email: amirfarnzad@yahoo.com
github_username:  amirfarnzad
linkedin_username: amirfarnzad


about_profile_image: images/profile.jpg
about_content: |
  CV: [PDF](https://amirfarnzad.github.io/CV.pdf)
  
  As a dedicated <mark>Biotechnology</mark> student with a deep passion for exploring the complexities of science and business,
  I am driven by a strong interest in pursuing a Master's degree in <mark>Business Management</mark>.
  This stems from my recognition of the critical role that effective business strategies play in the successful translation of biotechnological breakthroughs into practical applications that benefit society.
  

content:
 
  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Islamic Azad University
        caption: 2021 - 2025
        sub_title: Bachelor of Science, Biotechnology
     
      - layout: top-middle
        title: National Organization for Development of Exceptional Talents
        caption: 2015 - 2021
        sub_title: Student, Science
      

remote_theme: mo-shakiba/intCV

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
